"""Add news_sentiments table

Revision ID: 909acfba8ca8
Revises: 124236abc3de
Create Date: 2026-09-19 19:50:31.637099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909acfba8ca8'
down_revision: Union[str, Sequence[str], None] = '124236abc3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_sentiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_sentiments_stock_id'), 'news_sentiments', ['stock_id'], unique=False)
    op.create_index(op.f('ix_news_sentiments_timestamp'), 'news_sentiments', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_sentiments_timestamp'), table_name='news_sentiments')
    op.drop_index(op.f('ix_news_sentiments_stock_id'), table_name='news_sentiments')
    op.drop_table('news_sentiments')
    # ### end Alembic commands ###
